### ISSUE TITLE
v:content.render

### ISSUE THREAD

**Issue by jwittorf** [FluidTYPO3/vhs#1327] opened 2017-06-23 14:05 UTC
Using:

* TYPO3 8.7.2
* VHS dev-development (https://github.com/FluidTYPO3/vhs/commit/40ea0d74bd54dc501f16bb3d5f5074127ef23f87)

When using `<v:content.render column="0"/>` this error occurs:

```
Argument 1 passed to FluidTYPO3\Vhs\ViewHelpers\Content\AbstractContentViewHelper::getRenderedRecords()
must be of the type array, null given, called in
L:\htdocs\t3.domain\typo3conf\ext\vhs\Classes\ViewHelpers\Content\AbstractContentViewHelper.php on line 111
```

It should be possible to just render the content of a specific column on the users current page. I've been using the simple form of `<v:content.render column="X" />` for quite some time now working like a charm and need it working again as it should.

The [docs](https://fluidtypo3.org/viewhelpers/vhs/development/Content/RenderViewHelper.html) don't indicate that anything has changed on how to use it except for the new possibility to `Render a single content element by its UID` but this is not what I'm intending to do and what the function should be able to do.

**Comment by DanielSiepmann** [comment] 2017-08-28 14:41
I do not get an error, but the whole content of a page when using column "0" in Version 4.3.0.
The reason is that there is a type cast and 0 is a number which in the used condition is false with fallback to render whole page.

**Comment by NamelessCoder** [comment] 2017-08-28 14:47
Hi guys - please try the fix in the linked pull request and report back if that prevents both of your issues! Thanks :)

**Comment by dahaupt** [comment] 2017-08-28 20:46
@NamelessCoder Hi there, I've got a different error message coming with version **4.3.0** using `<v:content.render column="0"/>`:

`#1257246929: Tried resolving a template file for controller action "Content->render" in format ".html", but none of the paths contained the expected template file ().`

With #1362 it's working again!

**Comment by NamelessCoder** [comment] 2017-08-28 20:50
@dahaupt The error you got there indicates you may have a content element that's incorrectly configured and only got rendered because of the bug with colPos 0. For example it could be in a colPos that isn't part of the layout. The patch in #1362 just hides the issue with that element by avoiding rendering it so be careful you don't trip over this other element in another context!

**Comment by dahaupt** [comment] 2017-08-28 22:46
@NamelessCoder Thanks for that information. I anyway had a mistake in my template using the `colPos` value for `column` in `<v:content.render column="0"/>`. I changed it using the name of the specific column and now it's working fine (reading docs carefully works 😄) . 

Sorry for the confusion in this matter.

**Comment by NamelessCoder** [comment] 2017-08-28 22:57
I just noticed a bit of confusion in the VH docs. The `column` argument is of type integer but says it wants the "name" of the column. A few minutes ago I pushed a change to change that so it clearly says it wants the column position number (colPos). Hopefully you didn't get caught on that and tried using the name of the column as entered in the grid or backend layout - because that would be cast to an integer and select content from colPos=1.

From your code example it looks like you got the integer colPos so that's good! :)

**Comment by tantegerda1** [comment] 2017-08-29 12:05
Maybe this is the problem (see my comment): https://github.com/FluidTYPO3/vhs/commit/d403a95985ef6cdbf1482f05dbe613a4e3125b2b#commitcomment-23944709

**Comment by erredeco** [comment] 2017-08-29 12:25
I've rolled back to the previous version for the moment. I'll try to test it if I can.

**Comment by NamelessCoder** [comment] 2017-08-29 15:53
@erredeco Would you mind pasting the line of Fluid template code you've got that calls this ViewHelper? Maybe I can track down why the patch didn't work for you.

**Comment by erredeco** [comment] 2017-08-30 07:42
@NamelessCoder well...that's just:

`<v:content.render column="0" />`

**Comment by tantegerda1** [comment] 2017-08-30 07:49
@erredeco  just out of curiosity: have you set `config.sys_language_overlay` in your TypoScript? If so, does temporarily removing it suppress the error?

**Comment by erredeco** [comment] 2017-08-30 08:04
@tantegerda1 yes, I've set
```
config.sys_language_mode = content_fallback
config.sys_language_overlay = hideNonTranslated
```
after commenting the first line, the patch started to work.

**Comment by DanielSiepmann** [comment] 2017-08-30 10:20
Works for me too. Still I've the mentioned issue with languages. But that's part of different issue.

**Closed** 2017-08-30 11:55 UTC

**Comment by bobviivi** [comment] 2017-09-11 16:34
/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php

to fix LN: 137
`        if (null !== $GLOBALS['TSFE']->sys_language_contentOL &&  filter_var($GLOBALS['TSFE']->sys_language_contentOL, FILTER_VALIDATE_INT) !== false  ) {
            $languageUids[] = $GLOBALS['TSFE']->sys_language_contentOL;
        }` 

without this AND --> Database error -->   sys_language_uid is integer

**Comment by DanielRuf** [comment] 2017-09-12 09:44
https://github.com/FluidTYPO3/vhs/issues/1327#issuecomment-325915031

This is reproducible and the cause on my end, can we still get the content somehow if this is set?

**Comment by NamelessCoder** [comment] 2017-09-12 09:53
Please try https://github.com/FluidTYPO3/vhs/pull/1366

**Comment by DanielRuf** [comment] 2017-09-12 10:04
> Please try #1366

This solves it. When do you plan to merge and release this or do you need some more testers?

**Comment by DanielRuf** [comment] 2017-09-12 10:07
But there seems to be some caching related issue (mentioned in https://github.com/FluidTYPO3/vhs/issues/1380).
