### ISSUE TITLE
[BUG] Problems with German umlauts in file names

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/vhs#804] opened 2015-03-31 14:14 UTC
If you add an image with German umlauts there are problems with vhs VHs.
E.g. image name ```Würzburg.jpg```:
The link in filelist (working) ```/fileadmin/media/Bilder/slider/W%C3%BCrzburg01b.jpg```
With this code in ```<f:section name="Preview">```
```<f:for each="{v:content.resources.fal(field: 'bild')}" as="image">
    <v:resource.image treatIdAsReference="TRUE"  identifier="{image.uid}"  width="200"/>
  </f:for>```
I'm getting ```W%25C3%25BCrzburg01b.jpg``` in the backend
Same problem with this code
```<v:resource.image identifier="{v:content.resources.fal(field: 'bild') -> v:iterator.extract(key: 'id')}" as="resources">
  <f:for each="{resources}" as="fileimage">
    <img src="{fileimage.source}" alt="{fileimage}" width="150" />
  </f:for>
</v:resource.image>```

With this code
```<v:content.resources.fal field="bild" as="images">
  <v:condition.type.isArray value="{images}">
    <f:then>
      <f:for each="{images}" as="image" iteration="iteration">
        <v:media.image src="{image.url}" alt="{image.alternative}" width="200" />
      </f:for>
    </f:then>
  </v:condition.type.isArray>
</v:content.resources.fal>```
I'm getting the message ```Could not get image resource for "fileadmin/media/Bilder/slider/W%C3%BCrzburg01b.jpg".```
althoung the link is correct!

**Comment by bjo3rnf** [comment] 2015-04-03 06:13
If I add an image with umlauts those get transliterated so in my case ``Würzburg.jpg`` would be renamed to ``wuerzburg.jpg`` thus I can't reproduce the issue. Is there some setting to control this?

**Comment by ste101** [comment] 2015-04-16 15:28
Could you try the TYPO3 option ```'UTF8filesystem' => '1'```

**Comment by xf-** [comment] 2015-07-23 17:03
hi,
i think this is a bad option.
e.g. Turn it on and add a file in filelist with specialchars and i get an error.

We don't touch encoding.
Filemounts and filesystems can cause the next problems.

I will talk with other developers, but i think we should close this task. Playing with encoding is a bad idea. It looks like URL encode, you can use https://fluidtypo3.org/viewhelpers/vhs/master/Format/Url/DecodeViewHelper.html before.

**Comment by xf-** [comment] 2015-07-23 17:20
I talked with others, we don't want to cause problems with mounts and other stuff. We relay on T3core.
You can try the decode

**Closed by xf-** 2015-07-23 17:20 UTC

**Comment by darthnorman** [comment] 2025-01-24 16:59
You can use the 'asObjects' argument inside v:content.resources.fal to get around that problem. Putting the path through v:format.url.decode would also work but the first option is the preferable way.
