### ISSUE TITLE
vhs Version 4.1.0: v:iterator.explode does not explode

### ISSUE THREAD

**Issue by ZYZ64738** [FluidTYPO3/vhs#1269] opened 2017-03-08 07:48 UTC
Hi there,

`<v:iterator.explode as="images" content="{panel -> f:cObject(typoscriptObjectPath:'lib.gridelementsContentImages')}" glue=",">
`

does simply not explode my commasparated list into an array. Furthermore it just prinouts this list.

Same code works like expected under vhs Version 3.1.0

**Comment by monosize** [comment] 2017-03-08 07:52
Hi, see #1254
ZYZ64738 <notifications@github.com> schrieb am Mi. 8. März 2017 um 08:48:

**Comment by bjo3rnf** [comment] 2017-04-14 07:26
Closing as duplicate of #1254. Please follow the discussion over there.

**Closed by bjo3rnf** 2017-04-14 07:26 UTC
