### ISSUE TITLE
FalViewHelper Crashes in TYPO3 Backend v9.5.3

### ISSUE THREAD

**Issue by chriskrj** [FluidTYPO3/vhs#1551] opened 2018-12-14 12:53 UTC
Now after TYPO3 Update to 9.5.3 Backend Preview calls Exception, when using 
`v:content.resource.fal` in Preview Section.

```html
<f:section name="Preview">
  <v:content.resources.fal field="settings.falimage" as="images" record="{record}">
    <f:for each="{images}" as="image">
      <f:if condition="{image}">
        <f:image src="{image.id}" treatIdAsReference="1" maxWidth="100"/>
      </f:if>
    </f:for>
  </v:content.resources.fal>
</f:section>
```

Exception in Backend says:
`Call to a member function exec_SELECTgetRows() on null`

TYPO3 9.5.3
vhs 5.1
flux 9.1
php 7.2.12

**Comment by chriskrj** [comment] 2018-12-18 15:48
The Database  $GLOBALS['TYPO3_DB'] got removed in TYPO3 9.5. A Solution for now would be to install [ typo3db-legacy](https://packagist.org/packages/friendsoftypo3/typo3db-legacy) extension, but i actually don't want to use a legacy Ext. for now.
Are there any other solutions?

**Comment by dmitryd** [comment] 2019-01-07 13:52
I could not find any usage of `exec_SELECTgetRows` in the current `development` branch (except `FalViewHelperTest`). So I guess this is fixed with the exception of the test class.

**Comment by NamelessCoder** [comment] 2019-04-22 17:52
Crash no longer happens - usage in BE aspect is duplicate of #1500.

**Closed by NamelessCoder** 2019-04-22 17:52 UTC
