### ISSUE TITLE
v:variable.set caching problem

### ISSUE THREAD

**Issue by pravin-vavadiya** [FluidTYPO3/vhs#1389] opened 2017-09-21 05:13 UTC
I have using TYPO3 8.7 latest version with vhs 4.3.2

i use v:variable.set in my template file like below.

> **<v:variable.set name="data" value="my custome viewhelper"> </v:variable.set>**

it's working sometime but after clear the cache variable unset or empty value.

**Comment by NamelessCoder** [comment] 2017-09-21 11:56
I haven't been able to reproduce this, neither with Fluid standalone itself or with VHS on TYPO3v8 (they both use the exact same method of assigning the variable). It is possible this is caused by that variable being reset or not passed for other reasons.

One thing though, you should self-close the tag when you set the value property. That way there's no confusion what the value becomes:

```
<v:variable.set name="data" value="my custome viewhelper" />
```

This removes the possibility that any whitespace gets used as value instead of the intended argument.

This issue is a duplicate of https://github.com/FluidTYPO3/vhs/issues/1334 so I will close it. Don't forget to check the list of open and recently closed issues before you open new ones!

**Closed by NamelessCoder** 2017-09-21 11:56 UTC
