### ISSUE TITLE
vhs 4.0 problem with typo3 content type -special menus-

### ISSUE THREAD

**Issue by pauweh** [FluidTYPO3/vhs#1253] opened 2017-02-17 09:45 UTC
Using vhs v3.10 with typo3 7.6.15 all is fine with the content-elements of type -special menus-.
Some special menus are rendered in the footer of the website to show menus of pages with categories.
The update to vhs 4.0 (clearing caches, even clearing typo3temp folder) will not show the special menus any longer. The elements are empty - at least at the second rendering of the page and then forever. The first rendering of the page still shows some of the menus - after the second rendering the menus all are empty.
Return to vhs v3.10 using extension-manager and all is fine again.

The elements are included in the FluidTemplate via typoscript:
<f:cObject typoscriptObjectPath="footer.WebsiteMenu"/>
The typoscript:
footer.WebsiteMenu = RECORDS
footer.WebsiteMenu {
	tables = tt_content
	source =  1234
}

**Comment by bjo3rnf** [comment] 2017-04-14 07:24
Closing as duplicate of #1272

**Closed by bjo3rnf** 2017-04-14 07:24 UTC
