### ISSUE TITLE
Class "TYPO3\CMS\Extbase\Object\ObjectManagerInterface" not found(TYPO3 8.7)

### ISSUE THREAD

**Issue by pravin-vavadiya** [FluidTYPO3/vhs#1385] opened 2017-09-14 04:59 UTC
I have used TYPO3 8 Latest version with repository extension fluidpages, fluidcontent, flux and vhs(latest version) with my own typo3 template extension and my systems using php version 7.1.99.

in frontend i getting error "Class "TYPO3\CMS\Extbase\Object\ObjectManagerInterface" not found(TYPO3 8.7)"

**Comment by cedricziel** [comment] 2017-09-14 07:07
Can we have a stacktrace?

**Comment by pravin-vavadiya** [comment] 2017-09-14 11:23
![screenshot](https://user-images.githubusercontent.com/30591061/30427361-2bfd42f4-996d-11e7-8ba5-ce2cd9c889f8.png)

**Comment by Fisher42** [comment] 2017-09-14 11:35
With 7.6 I get a similar exception: 
`Cannot instantiate interface TYPO3\CMS\Extbase\Object\ObjectManagerInterface`
![screenshot_2017-09-14_13-33-37](https://user-images.githubusercontent.com/1522981/30427746-3aa45ec6-9951-11e7-9fc6-2627fb0707b4.png)
The exception occurs when using the UncacheViewHelper:
`                <v:render.uncache partial="Bootstrap/Search/Field/{searchField.partialName}"
                                  arguments="{searchField: searchField, searchId: searchId}"
                                  section="Main"/>`
Reverting to 4.2 makes the exception disappear.

**Comment by cedricziel** [comment] 2017-09-14 12:05
Hmm @NamelessCoder, the commit is missing from the latest release, can you check what's wrong?

**Comment by pravin-vavadiya** [comment] 2017-09-14 12:18
Hello, 

thanks for your time @cedricziel and @Fisher42 

If we removed **<v:render.uncache partial="Content/Uncached" />** tag then it's working fine.
But why it is not **<v:render.uncache** working for typo3 latest version(8.7).

Thnks a lot @Fisher42 really appreciated for your help.

**Comment by cedricziel** [comment] 2017-09-14 12:22
@pravin-vavadiya i fixed the issue in a recent pull request. I Just double checked the latest tag and the commit is missing. You can fix your issue by switching to the development branch.

**Comment by NamelessCoder** [comment] 2017-09-14 12:27
Nothing is wrong - 4.3.1 is a dummy release with metadata change only, as requested in the security PSA. I'm guessing the TER folks would like to run a comparison to detect if any extensions were actually modified unexpectedly, so they can release a followup saying "all green".

**Comment by cedricziel** [comment] 2017-09-14 12:36
Alright, could you prepare 4.3.2 then? :)

**Comment by NamelessCoder** [comment] 2017-09-14 12:38
Once we have https://github.com/FluidTYPO3/vhs/pull/1366, yes - just so I don't have to do another release tomorrow ;)

**Comment by pravin-vavadiya** [comment] 2017-09-15 03:55
@cedricziel ,

sorry i could not found your latest commit in development branch.

**Comment by Fisher42** [comment] 2017-09-15 07:36
Isn't this a duplicate of #1368?

**Comment by NamelessCoder** [comment] 2017-09-15 13:28
Solved in dev-development, TER release is pending.

**Closed by NamelessCoder** 2017-09-15 13:28 UTC

**Comment by pravin-vavadiya** [comment] 2017-09-18 06:25
@cedricziel Can you please share development branch link here?

**Comment by cedricziel** [comment] 2017-09-18 07:27
@pravin-vavadiya : What do you mean? It's the development branch of the git repository.
