### ISSUE TITLE
variable.register.set Viewhelper not available in Template with f:cobject

### ISSUE THREAD

**Issue by varioous** [FluidTYPO3/vhs#1757] opened 2022-03-23 19:29 UTC
I register a variable in a Fluid template:
` <v:variable.register.set name="subCategoryHeader" value="{v:content.render(column: 2)}" />`
After that i render a Plugin via f:cObject:
`<f:cObject typoscriptObjectPath="lib.searchresult" />`

In the Fluid template of "lib.searchresult" the registered variable is only available the first time/call (when the cache is build). In the second following calls the variable {subCategoryHeader} is empty. When calling the page uncached everything is working correctly.

In this case the lib.searchresult is the Solr Result-Page. Here is the corresponding TypoScript:
`lib.searchresult < plugin.tx_solr_PiResults_Results`

**Comment by NamelessCoder** [comment] 2022-03-27 10:04
I'm afraid there's nothing I can do about that. The `v:variable.register.set` ViewHelper uses methods from TypoScriptFrontendController which are outside the scope of VHS. As such, the problem would be the same whether or not VHS or something else was used to set the variables.

You may want to report this to the [TYPO3 core bugtracker](https://forge.typo3.org/projects/typo3cms-core/issues). But it could be done this way by design.

**Comment by NamelessCoder** [comment] 2022-05-01 14:31
Closing as "cannot solve".

**Closed by NamelessCoder** 2022-05-01 14:31 UTC
