### ISSUE TITLE
v:content.render column="0" and spamProtectEmailAddresses not working

### ISSUE THREAD

**Issue by OrangeLeinad** [FluidTYPO3/vhs#1456] opened 2018-03-14 07:52 UTC
In TYPO3 V8.7.10 with the current Version 4.4.0 of Ext:vhs , mailaddresses are not spam protected if you use 

**<v:content.render column="0" />** 

combinated with 

config.spamProtectEmailAddresses = -5
config.spamProtectEmailAddresses_atSubst = (at)

If I choose previous Version 4.3.3 it works fine.

**Comment by OrangeLeinad** [comment] 2018-03-14 09:40
For your info. I just tested Ext:vhs V4.4.0 with the new update TYPO3 V8.7.11, which was released yesterday. And this combination works fine too.

**Comment by grimmcreative** [comment] 2018-03-14 09:42
Can confirm this, works perfect.

**Comment by cedricziel** [comment] 2018-03-14 10:10
Soo.. can we close it? Sounds like a core issue.

**Comment by NamelessCoder** [comment] 2018-03-14 15:30
Not related to VHS as far as I can tell. The method(s) responsible for that conversion are all in the TYPO3 core, not VHS. Since 8.7.11 was a regression fix release I suppose this was one of the regressions that fixed.

**Closed by NamelessCoder** 2018-03-14 15:30 UTC
