### ISSUE TITLE
Variables not resolved in v:page.header when using space indentation

### ISSUE THREAD

**Issue by typecat** [FluidTYPO3/vhs#1341] opened 2017-07-24 14:53 UTC
I'm not sure whether this is a VHS or a core bug, so I try it here first.

Using the following code snippet with tab indentation worked fine. After switching to spaces fluid variables inside the v:page.header view helper weren't resolved any more.

<v:page.header>
      <style media="screen">
        @media (max-width: 769px) {
          .background {
            background-image: url('/{imageMobile.originalResource.publicUrl}')
          }
        }

        @media (min-width: 769px) {
          .background {
            background-image: url('/{imageDesktop.originalResource.publicUrl}')
          }
        }
      </style>
</v:page.header>

I traced it down to TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\AbstractNode::evaluateChildNodes(), but couldn't really understand what exactly the cause is.
My workaround for now is to remove any indentation within <v:page.header>, but it's not the best way of course.

TYPO3 7.6.20 using css_styled_content
VHS 4.2.0

**Comment by NamelessCoder** [comment] 2017-07-25 16:40
To prevent this, disrupt one or more of the opening or closing braces in the CSS by using `<f:format.raw>` around them. You need to break the parser pattern for inline ViewHelper calls which matches the expression above.

This is by the way a Fluid issue, not caused by VHS but the same problem you'd face with any Fluid-based inline CSS. Some expressions are so close to Fluid syntax that they get matched.

**Closed by NamelessCoder** 2017-07-25 16:40 UTC

**Comment by typecat** [comment] 2017-07-26 09:00
Of course, the curly braces! Thank you, fixed that in my project. But it's still weird that it works with tabs, but not with spaces.
