### ISSUE TITLE
v:asset.script incompatible with PHP 7.3

### ISSUE THREAD

**Issue by herrhamann** [FluidTYPO3/vhs#1600] opened 2019-10-08 08:05 UTC
I include multiple JS files with v:asset.script. With PHP 7.3 the generated file are corrupted. The conten of some files is completly missing and in other files the content is incomplete. See attached files for comparison. One is generated with PHP 7.2 the other with PHP 7.3, both with the same set of JS files. I tried with standalone on and off, no difference. With debug=1 everything seems to be ok, no hint for an error. Tested with vhs 5.1 / 5.2 and typo3 8.7.27.

[vhs-generated-js-php7.2.txt](https://github.com/FluidTYPO3/vhs/files/3701342/vhs-generated-js-php7.2.txt)
[vhs-generated-js-php7.3.txt](https://github.com/FluidTYPO3/vhs/files/3701343/vhs-generated-js-php7.3.txt)

**Comment by tantegerda1** [comment] 2019-10-08 11:20
Are the different php versions configured the same way? Settings from open_basedir to activated extensions come to mind… (Just a wild guess - to be ruled out).

**Comment by herrhamann** [comment] 2019-10-09 14:02
Yes, both php versions are configured the same way.

**Comment by NamelessCoder** [comment] 2019-10-10 14:25
Hi @herrhamann,

We need a bit more information - for example, do you use `fluid="1"` on the asset indicating you want it parsed as Fluid, and are you therefore perhaps affected by the PCRE bug described on https://github.com/TYPO3/Fluid/issues/449?

There is nothing in VHS itself that should cause anything like this, depending on PHP versions. For sure, if you integrate these files as raw assets there should be zero difference.

**Comment by herrhamann** [comment] 2019-10-14 07:18
Hi @NamelessCoder, 
yes i am using fluid="1" on the affected assets. I'll give the PCRE Bug a try

**Comment by NamelessCoder** [comment] 2020-01-08 12:12
Closing; not caused by VHS - perhaps related to PCRE or Fluid version. If you're not using Fluid source code within the assets, avoid using `fluid="1"` on the `v:asset.*` tag.

**Closed by NamelessCoder** 2020-01-08 12:12 UTC
