### ISSUE TITLE
v:menu and useShortcutUid

### ISSUE THREAD

**Issue by timofo** [FluidTYPO3/vhs#1422] opened 2017-11-21 13:51 UTC
TYPO3 8.7.8
vhs 4.3.3
(with vhs 4.3.2 it is working!)

Simple use with a page with a shortcut:
<v:menu pageUid="1" useShortcutUid="1">
</v:menu>

The ID of the target page is not there. It is the ID from the shortcut page.

**Comment by NamelessCoder** [comment] 2017-11-21 14:46
`useShortcutUid` is by design _supposed to use the shortcut page's ID_ as the name infers. Were you looking for `useShortcutTarget`?

**Comment by timofo** [comment] 2017-11-21 15:02
In the documentation is for useShortcutUid: "If TRUE, substitutes the link UID of a shortcut with the target page UID."
Yes that works till version 4.3.2
But with version 4.3.3 the link UID is NOT substituted. It is the original UID. Not the shortcutid.

**Comment by bjo3rnf** [comment] 2017-11-21 16:22
Must be related to 1d5166dd107884a2d94542b6641c5a5ac4e24b0a

**Comment by bjo3rnf** [comment] 2017-11-21 16:25
...which makes no sense to me after taking a closer look. Who on earth merged this PR? ^^

**Comment by bjo3rnf** [comment] 2017-11-21 16:28
Mind giving https://github.com/bjo3rnf/vhs/tree/fixfix a try?

**Comment by timofo** [comment] 2017-11-21 16:43
This fixes the issue. :-)

**Comment by tantegerda1** [comment] 2017-11-28 07:40
I was the one who committed the wrong patch. Sorry for that!

This is the documentation to the `useShortcutUid` parameter:
> If TRUE, substitutes the link UID of a shortcut with the target page UID (and thus avoiding redirects) but does not change other data - which is done by using useShortcutData.

Does that still hold true?

**Comment by bjo3rnf** [comment] 2017-11-28 07:44
> I was the one who committed the wrong patch. Sorry for that!

And I was the one who merged it. Sorry for that as well.

> Does that still hold true?

Yes, it does.

**Closed** 2017-11-28 08:04 UTC

**Comment by cedricziel** [comment] 2017-11-28 08:05
Revert-fix-merged. Thx to any of you :)
