### ISSUE TITLE
v:media.video preload doesn't work

### ISSUE THREAD

**Issue by Williwurstig** [FluidTYPO3/vhs#1443] opened 2018-02-01 16:50 UTC
If you set the argument preload, the output is preload="preload".
`<v:media.video src="{image.originalFile.publicUrl}" preload="none"
                                                   width="1150" height="476"`
output: 
`<video width="1150" height="476" preload="preload"><source src="Headervideo_Farbauflo__sung_kl.mp4" type="video/mp4" /></video>`

VideoViewHelper.php Line 175:
`$tagAttributes['preload'] = 'preload'`
must be changed to:
`$tagAttributes['preload'] = $this->arguments['preload'];`

**Comment by neufeind** [comment] 2018-10-30 23:01
For video that is already fixed. Duplicate of #1308.
Unresolved for audio.

**Closed** 2018-10-31 12:16 UTC
