### ISSUE TITLE
Variable / GetViewHelper fails on dynamic numeric index

### ISSUE THREAD

**Issue by ikkez** [FluidTYPO3/vhs#848] opened 2015-06-16 12:50 UTC
This line of code https://github.com/FluidTYPO3/vhs/commit/78f88ec57bde3d8e5196b08c35ea16c5b34f297c#diff-442f997294940cebb08db28d7ec68f2eR59
fails if `$value` is just a simple array, containing only particular numeric keys. In example if you want to call `{v:variable.get(name: 'formErrors.fieldX.{cUID}')}`, with `cUID` being `230` and `formErrors.fieldX` contains an array like
```php
Array(
  50 => Array(...)
  84 => Array(...)
  230 => Array(...)
  325 => Array(...)
)
```
this foreach loop would never reach the key *230*, since it depends on `$index` and the assumption that the length of `$value` as long as its biggest key. In fact, the foreach loop ends after the 4th iteration without selecting the correct segment. Using the real **key** fixed the problem in my case:

```php
foreach ($value as $key=>$possibleValue) {
	if ($key === $segment) {
		$value = $possibleValue;
		break;
	}
}
```
regards.

**Comment by NamelessCoder** [comment] 2015-06-16 14:17
This one is likely because `ctype_digit` returns FALSE on a string/number longer than 1 char. A different check for "is input key numeric?" is needed. E.g. it is not a case of an array returning early or not at all - it's a case of the loop never beginning in the first place because of the surrounding check. Just in case someone wants to fix it.

**Comment by ikkez** [comment] 2015-06-16 14:36
> `ctype_digit` returns FALSE on a string/number longer than 1 char

That's not true, see http://php.net/manual/en/function.ctype-digit.php

And `ctype_digit` is not the problem in my case. The check works corrently and the loop started fine... I xdebugged it. It's because the loop is weird. I read your comment there, and I guess there is a good reason for that, but maybe you can check if $value is an instance of ObjectStorage or just a simple array.
Or maybe just extend it to `if ($index === $segment || $key === $segment)`

**Comment by NamelessCoder** [comment] 2015-06-16 22:38
Depending on which index you request and which type your input variable has you might not get the expected result, because of `ctype_digit`s slightly unpredictable behavior - although it may not be the cause of the problem you face, it certainly will be a problem at some point.

The other part is that this code doesn't care wether `$value` is an array or ObjectStorage and so starts iterating and counting in both cases, which obviously causes unexpected returns if the input is an array with nonsequential indices.

I would happily accept a pull request which switches to ObjectAccess::getPropertyPath - I'm fairly sure the code as it is now is behaviorally identically to this piece in VHS, with iteration of ObjectStorage to get numerical indices, and we would need to switch to it sooner or later anyway. Doing that should also work around your current problem. The one case it wouldn't support that way is custom ObjectStorage/Iterator instances - but there's already a core patch queued for that: https://review.typo3.org/#/c/39585/

**Comment by ikkez** [comment] 2015-07-15 10:31
for now it also works if I just use the `useRawKeys` option.

**Comment by NamelessCoder** [comment] 2015-07-22 21:06
`useRawKeys` is a perfectly valid solution for this. The coming versions of TYPO3 should support this natively in the ObjectAccess class so I take the liberty of closing this one; expecting to delete much of the code in this ViewHelper and replacing it with a good old `ObjectAccess::getPropertyPath`.

**Closed by NamelessCoder** 2015-07-22 21:06 UTC
