### ISSUE TITLE
MountPoints are not properly recognized with VHS Menus

### ISSUE THREAD

**Issue by phifa** [FluidTYPO3/vhs#1104] opened 2016-08-25 14:59 UTC
Title says it all. TS Menu works, VHS Menu fails. Instead of proper use of mount point, it is more a shortcut. Actually links into the mounted page.

**Comment by cedricziel** [comment] 2016-08-25 15:11
Ref: #552

**Comment by einpraegsam** [comment] 2016-08-29 12:53
Same for us. Links are simply rendered wrong. Mountpoints with <v:page.menu.directory /> are acting like shortcuts. The basic use of a mountpoint is to change the path (and maybe domain) and not to crosslink. 
A ref to #552 does not help anyone in my eyes. It seems to be closed - or am i wrong here?

**Comment by cedricziel** [comment] 2016-08-29 13:03
Yup, it's been closed.

#552 was a pull request, so no need to discuss the problem there - this issue is meant to provide the platform for discussing the topic.

Would you mind helping fixing the faulty behaviour?

**Comment by einpraegsam** [comment] 2016-08-29 13:09
I could ask for money from the customer to get this issue fixed!?

**Comment by NamelessCoder** [comment] 2016-08-29 16:53
This issue is more complicated than it may seem on the surface. When you render a TS menu TYPO3 has a very easy time creating a new sub-context when encountering a mount point. When we do this from PHP/ViewHelpers it requires a **lot** of additional decisions, as @bjo3rnf can likely testify.

One of our goals with VHS is to limit the amount of code that **we** need to implement and use as much of the TYPO3 core as possible (so that VHS becomes primarily an API for using more parts of TYPO3 directly from within Fluid). So it collides with our goals to have to implement a big chunk of mount point handling - when from our perspective, the problem is that the TYPO3 core itself does not provide any real API to rendering a menu programmatically. Fluid Styled Content also suffers from this drawback in its menu ViewHelpers - so we're not alone in this.

Knowing the above we face a situation where we *could* implement this in VHS but would much rather not. The ideal solution which also solves the problem for Fluid Styled Content (not `fluidcontent_core` but `fluid_styled_content` mind you - the core extension, not ours) however would be to implement this in the TYPO3 core - since VHS is not a core extension, our implement would not solve the problem for Fluid Styled Content and inevitably, they would end up creating a similar solution.

At this point you may ask then "why isn't VHS a core extension?" and part of the answer to that question, is that VHS does exactly (by necessity) recreate some previously TS-only APIs in PHP form *and cannot completely get the job done with core classes only*. If we had been able to do that, it would be a mere formality to import the menu and other ViewHelpers into the TYPO3 core (they would essentially just be empty shells which collect arguments and delegate to the **rewritten and improved** core menu rendering classes). This is done from a standpoint of efficiency and speed much more than improving the TYPO3 core (and that in turn is a decision which also has some old causes which I'm happy to say no longer are as relevant, but they're certainly not relevant here): this way we were able to provide a solution *now* and improve that solution, then attempt to advocate that the core adopt our solution once it proves itself.

Which I think it has at this point. So now, I think we are indeed ready to attempt to improve TYPO3's menu rendering API and decouple it a bit from being a TS-only feature to something that plays nice with things like ViewHelpers - and fit that solution with ViewHelpers that provide the same functionality as the current VHS menu suite (read: are copies of that API and behavior).

**This is our preferred solution. One that benefits everyone instead of just VHS, one that we don't need to maintain and worry about - and one that would allow us to take the much awaited step of including more of VHS into TYPO3 itself.**

If you wish to contribute to getting this done then of course we (or at least I... since I should probably only speak for myself here) are happy to help create that TYPO3 core feature. *But we will not be attempting to provide this feature from VHS and would most likely also reject pull requests to add it to VHS*. As with any rule there are exceptions but as far as I can tell and have analysed my way through so far, any attempt to implement this in VHS would inevitably become a huge change and one that carries so many problems related to edge cases that we could not possibly (or maybe feasibly is a better word) make any assertions about supported usage aside from really simple stuff.

I unfortunately couldn't give you any sort of estimate on this but at the very least I'm guessing it's a couple days of work and possibly the same to review/argue it into TYPO3. So it is a significant chunk of money to have to ask a customer for (and for that, I apologise, but I don't see any easy/quick/cheap fix here).

**Comment by NamelessCoder** [comment] 2016-08-29 16:55
I will now close this and other mount point rendering related issues, with a reference to the above. Should anyone wish to help create or sponsor a solution like the one described above, you are more than welcome to contact me or another team member directly and ask how to proceed. 

Sorry about the inconvenience guys. Hope you understand :)

**Closed by NamelessCoder** 2016-08-29 16:55 UTC
