### ISSUE TITLE
FAL image in Backend Preview fails for translated CEs (sys_language_id != 0)

### ISSUE THREAD

**Issue by dss-github** [FluidTYPO3/vhs#1558] opened 2019-01-07 18:38 UTC
https://github.com/FluidTYPO3/vhs/blob/e1252a8e598bdcc6150a240bf35c9c341fd6fe74/Classes/ViewHelpers/Resource/Record/FalViewHelper.php#L132

Somehow (at least in TYPO3 9.5.3, Flux 9.1) translated CEs seem to have the TSFE->sys_page object set.
So the condition above is true and the ViewHelper tries to render the backend-preview image as if it was in the frontend (which fails and sometimes causes oops errors in the backend...).
I think the condition is not working properly, because the TSFE is sometimes initialized in backend modules too. 
As a workaround I extended it like this: 
`if (empty($GLOBALS['TSFE']->sys_page) === false && TYPO3_MODE !== "BE") {`
and it seems to work for me.

**Comment by dmitryd** [comment] 2019-01-08 14:57
The most interesting thing is that the code does not use `$GLOBALS['TSFE']->sys_page` anywhere in the viewhelper except the condition. It would be nice to have a stack trace for the exception here...

**Comment by NamelessCoder** [comment] 2019-04-22 17:53
Duplicate of #1500 (at least, will be taken care of as part of that issue).

**Closed by NamelessCoder** 2019-04-22 17:53 UTC
