### ISSUE TITLE
render.uncache does not respect partialRootPath

### ISSUE THREAD

**Issue by ipf** [FluidTYPO3/vhs#849] opened 2015-06-23 08:38 UTC
In an extension I have explicitly set the partialRootPath to a non-default location. 
Using the v.render.uncache viewHelper to render a partial does - contrary to the f:render viewHelper not respect the set partialRootPath

**Comment by p2media** [comment] 2015-06-26 15:21
We are using `partialRootPaths.0 = ...` and having the same issue.

**Comment by xf-** [comment] 2015-07-26 00:50
please test again we changed a default setting 10 to 0 in flux.

**Comment by NamelessCoder** [comment] 2015-07-26 21:18
Taking a leap of faith here and assuming this is indeed caused by the index Flux uses. In which case this will be fixed next time you pull from development ;)

Thanks for reporting guys!

**Closed by NamelessCoder** 2015-07-26 21:18 UTC

**Comment by saphrus** [comment] 2016-06-08 15:50
Can anyone confirm this issue being fixed?
I just ran into the same problem with TYPO3 6.2.25 and VHS 2.4
