### ISSUE TITLE
vhs v4.10 (since vhs 4.0) returns empty special-menus (so still useless vhs since 4.0)

### ISSUE THREAD

**Issue by pauweh** [FluidTYPO3/vhs#1272] opened 2017-03-14 18:04 UTC
Posting this issue again, since vhs 4.1 still has same mayor bug as 4.0:

Using vhs v3.10 with typo3 7.6.16 all is fine with the content-elements of type -special menus-.
Some special menus are rendered in the footer of the website to show menus of pages with categories.
The update to vhs 4.0/4.1 (clearing caches, even clearing typo3temp folder) will not show the special menus any longer. The elements are empty - at least at the second rendering of the page and then forever. The first rendering of the page still shows some of the menus - after the second rendering the menus all are empty.
Return to vhs v3.10 using extension-manager and all is fine again.

The elements are included in the FluidTemplate via typoscript:
<f:cObject typoscriptObjectPath="footer.WebsiteMenu"/>
The typoscript:
footer.WebsiteMenu = RECORDS
footer.WebsiteMenu {
tables = tt_content
source = 1234
}

**Comment by bjo3rnf** [comment] 2017-03-24 19:28
Hi @pauweh,

I don't see where vhs is involved here? Mind providing some more details in this regard (or pointing to where I am not able to see the forest for the trees)?

Cheers
Björn

**Comment by timofo** [comment] 2017-04-03 09:07
I have maybe the same problem. 
Here is my code: 
`<ce:menu.categories categoryUids="{categoryUids}" as="contentElements" relationField="{data.category_field}" table="tt_content">
	<f:if condition="{contentElements}">
			<f:for each="{contentElements->v:iterator.sort(order:'DESC',sortBy:'date')}" as="contentElement" iteration="iterator">`
With version before 4.0 it worked like expected. 
But since 4.0 nothing is rendered. Like pauweh said. Clearing cache, first page hit. "some" menus are there but not all. Second page hit. Nothing is shown. 

If i change this line from :
`<f:for each="{contentElements->v:iterator.sort(order:'DESC',sortBy:'date')}" as="contentElement" iteration="iterator">`
to
`<f:for each="{contentElements}" as="contentElement" iteration="iterator">`
then it worked. But i have no sorting. Before 4.0 it worked with sorting.

**Comment by dermansi** [comment] 2017-04-04 14:58
The "doktypes" option in v:page.breadCrumb doesn't work in 4.0 and 4.1, too

**Comment by tomhatzer** [comment] 2017-04-05 12:51
We have the same problem. The error lies in v:iterator.sort(order:'DESC',sortBy:'date') as it's causing out of memory exceptions (by creating infinite loops or something like that) and even total crashes of Apache. It doesn't return anything due to this circumstances and the results are always empty. Had to switch back to f:for without sorting.

**Comment by bjo3rnf** [comment] 2017-04-14 06:59
@pauweh I still can't see where vhs is involved in your code. Could you please elaborate on this? @timofo and @tomhatzer are using `v:iterator.sort`. I'll have a look.

**Comment by bjo3rnf** [comment] 2017-04-14 07:18
Sorry, can't reproduce. `v:iterator.sort` works as designed here as well. Anyone else?

**Comment by pauweh** [comment] 2017-04-15 09:20
My vhs is used in FluidStyledContent\Partials\Menu\Type-3.html
adding a sort option to the typo3 type-3 menu = menu of content sections.
As you can see I am using v:iterator.sort , too.

PS. If you cannot reproduce the errors mentioned in this issue, I think we should have a look on php Version (php v7.06), the system we are running should not matter (Webhosted space with Linux here)
, but the php memory-limit seems to matter, here its 256MB or something like this.
I guess you are testing on a system with lots and lots of memory?
So you cannot find any errors ooccuring in "low" memory php systems on normal webspace?

The menu-file looks like this:
`
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	xmlns:ce="http://typo3.org/ns/TYPO3/CMS/FluidStyledContent/ViewHelpers"
	data-namespace-typo3-fluid="true"
	xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	v:schemaLocation="https://fluidtypo3.org/schemas/vhs-master.xsd">

<ce:menu.list pageUids="{pageUids}" includeNotInMenu="1" as="pages">

<f:if condition="{pages}">
<ul class="ce-menu ce-menu-3">
<f:for each="{pages}" as="page">
	<ce:menu.section pageUid="{page.uid}"
		column="{useColumns}"
		as="contentElements" type="{type}">
		<f:if condition="{contentElements}">
		<f:for each="{contentElements->v:iterator.sort(order: 'ASC', sortBy: 'header')}"
			as="contentElement">
		<li class="colPos-{contentElement.colPos}">
			<f:link.page pageUid="{page.uid}"
				section="c{contentElement.uid}">
				{contentElement.header}
			</f:link.page>
		</li>
		</f:for>
		</f:if>
	</ce:menu.section>
</f:for>
</ul>
</f:if>

</ce:menu.list>
</html>
`

**Comment by NamelessCoder** [comment] 2017-04-23 18:48
@bjo3rnf I think this one depends on the template being fully compilable so you may need to put the VH call in a separate partial (in case you're testing this with a content or page template that uses other VHs too).

But the out-of-memory error, I'm guessing that one is caused by some recursion happening in the list of categories (which would be outside our control and can only be prevented by not creating recursive structures in the content/categories listed). I doubt `v:iterator.sort` is responsible for that one.

**Comment by timofo** [comment] 2017-04-24 07:11
The problem is that with verison before 4.0 it worked like expected. So it hat something to do with some changes in the >= 4.0 versions.

**Comment by timofo** [comment] 2017-05-18 09:23
Update: my error with the empty menus and v:iterator.sort is gone. :-) Now my menus are correct. 
But i did not changed anything in my code. But maybe it has something to do with the PHP Version. Now i have PHP 7.0. I dont know what version i had before. Maybe PHP 5.6. 
But i did not changed the code and now it is working. The only thing that could be different is the PHP Version. But i am not sure. Did not looked at the version when i had the empty menu. But it could be 5.6.

**Comment by pauweh** [comment] 2017-05-18 10:22
No, version 7 is not the solution to this error. 
Since my first comment, the error occurs using php v7. 
As mentioned in my comment from 15. April, I guess its a memory problem. 
Do you have more free memory now on your v7-Installation as before with your older php version?

**Comment by timofo** [comment] 2017-05-18 10:41
I dont know. Did not compare this. But could be. It is the same website. Only PHP Version and settings could be different.

**Comment by NamelessCoder** [comment] 2017-05-18 11:58
This is just a note about the dependencies: VHS requires PHP7 now (and rolling back PHP versions is imho never the answer).

**Comment by NamelessCoder** [comment] 2020-01-08 12:35
Closing issue, cause is a change to how the variable assignment is done:

* If you do not provide an `as` argument the default variable name is used (for menus this is `menu`)
* If you do provide an `as` argument then that is used as variable name
* Variables are no longer leaked, meaning they are only available inside the tag. If you need to assign it outside (leak it) then switch to inline ViewHelper syntax, avoid use of `as` and chain with `f:variable` which declares such variables.

**Closed by NamelessCoder** 2020-01-08 12:35 UTC
