### ISSUE TITLE
Page resources in different languages and v:page.resources.fal 

### ISSUE THREAD

**Issue by ducatisti-bln** [FluidTYPO3/vhs#1105] opened 2016-08-27 13:34 UTC
Hi, 

i try to read all page resources from a translated page with v:page.resources.fal, but only in the default language (de) i have results. The translated pages has different images for the current language, but the result is null.

TYPO3 7.6.10
VHS 3.0.1

This is the TypoScript language config

`
config {
    language = de
    htmlTag_langKey = de-DE
    locale_all = de_DE
    linkVars = L
    uniqueLinkVars = 1

```
sys_language_uid = 0
htmlTag_langKey = de
locale_all = de_DE.utf-8
language = de
```

}

[globalVar = GP:L = 1]
    config.sys_language_uid = 1
    config.language = en
    config.htmlTag_langKey = en
    config.locale_all = en_EN.UTF8
[global]

[globalVar = GP:L = 2]
    config.sys_language_uid = 2
    config.language = it
    config.htmlTag_langKey = it
    config.locale_all = it_IT.UTF8
[global]
`

The VH v:resource.record.fal in languages EN or IT has the results from the default language. 

How i can solve this problem with the VHS VH? 

Greetings Michael

**Comment by ducatisti-bln** [comment] 2016-08-27 15:07
I have this workaround in FluidTYPO3\Vhs\ViewHelpers\Page\Resources\FalViewHelper.php :

`
/**
     * @return string
     * @throws Exception
     */
    public function getTable()
    {
        $table = parent::getTable();

        if(!$this->isDefaultLanguage() && $this->getField() == self::DEFAULT_FIELD && $table == self::DEFAULT_TABLE){
            $table = $table.'_language_overlay';
        }

        return $table;
    }
`

**Comment by lkappeler** [comment] 2016-11-30 11:48
I do have the same problem, implemented a similar solution, not sure if this is the correct way https://github.com/lkappeler/vhs/commit/9361272b6b39ac71df355fd56c76264dce4f24e0

**Comment by NamelessCoder** [comment] 2016-11-30 11:54
Please consider using the pre-associated versions of FAL ViewHelpers:

* `v:content.resources.fal` for content-element FAL relations: https://fluidtypo3.org/viewhelpers/vhs/master/Content/Resources/FalViewHelper.html
* `v:page.resources.fal` for page FAL relations: https://fluidtypo3.org/viewhelpers/vhs/master/Page/Resources/FalViewHelper.html

Using the correct ViewHelper means you do *not* have to configure the generic/arbitrary `f:resource.record.fal` https://fluidtypo3.org/viewhelpers/vhs/master/Resource/Record/FalViewHelper.html which is designed to work for arbitrary tables.

`v:page.resources.fal` already supports language handling. Closing the issue.

**Closed by NamelessCoder** 2016-11-30 11:54 UTC

**Comment by lkappeler** [comment] 2016-11-30 12:11
@NamelessCoder the `v:page.resources.fal` [adds the overlayFileds](https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Page/Resources/FalViewHelper.php#L73) to given page record and then passes the record to the [getResources](https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Resource/Record/FalViewHelper.php#L103) function. But there the added overlay fields are just ignored. And the resources added to the default page are returned instead of the resources added to the translated page.

**Comment by NamelessCoder** [comment] 2016-11-30 12:19
> But there the added overlay fields are just ignored. 

I'm afraid I don't get how they are ignored? When you fetch a language overlay for pages, the overlay record contains properties of the overlay, not the original default-language record. Maybe you could explain this in a bit more detail?

**Comment by lkappeler** [comment] 2016-11-30 13:10
IMO the getPageOverlay function is not updating the given records data eg. uid instead its adding the following fields to the record. The relations in the "sys_file_reference" table (uid_foreign) are referring to the "_PAGES_OVERLAY_UID".
```
_PAGES_OVERLAY => TRUE
_PAGES_OVERLAY_UID => '15' (2 chars)
_PAGES_OVERLAY_LANGUAGE => 1 (integer)
```

**Comment by froehlit** [comment] 2017-01-31 10:22
Hi,
because of the different translation handling from pages and all other elements, i think the way to solve the problem is to use TYPO3s `\TYPO3\CMS\Frontend\Page\PageRepository::getFileReferences` instead of  `\FluidTYPO3\Vhs\ViewHelpers\Resource\Record\FalViewHelper::getResources`.
The TYPO3 PageRepository returns the right translated fal resource, so we don't have to worry about all `_PAGES_OVERLAY*` properties.

Example:
```
protected function getSlideRecordsFromPage($pageUid, $limit)
{
    $pageRecord = $this->getRecord($pageUid);
    
    $pageRepository = GeneralUtility::makeInstance(PageRepository::class);
    $pageRepository->init(false);
    $resources = $pageRepository->getFileReferences($this->getTable(), $this->getField(), $pageRecord);

    if (null !== $limit && count($resources) > $limit) {
        $resources = array_slice($resources, 0, $limit);
    }
    return $resources;
}
```

**Comment by lkappeler** [comment] 2017-01-31 11:15
@froehlit Thanks for your suggestion. We are using TYPO3 7 LTS and the method seems to be removed in this version: [ClassRef](https://typo3.org/api/typo3cms/class_t_y_p_o3_1_1_c_m_s_1_1_frontend_1_1_page_1_1_page_repository.html)
(As far as I can remember we had a customer requirement to be able to render Videos from different remote sources in the slider and were not able to render them properly with the built in Methods to get FileReferences)

**Comment by froehlit** [comment] 2017-01-31 13:56
@lkappeler I dont't know why the [ClassRef](https://typo3.org/api/typo3cms/class_t_y_p_o3_1_1_c_m_s_1_1_frontend_1_1_page_1_1_page_repository.html) has no `getFileReferences` method, but the current TYPO3 7.6 [sources](https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/frontend/Classes/Page/PageRepository.php) has the method and i can't see any deprecated note. (I do not want to exclude, that I didn't understand how the API was generated :) )

**Comment by NamelessCoder** [comment] 2017-01-31 14:50
PageRepository->getFileReferences should be safe to use on all TYPO3 versions supported by VHS.
